name: Performance

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    name: ${{ matrix.generator }} ${{ matrix.compiler }} ${{ matrix.build_type }}
    runs-on: ubuntu-latest
    container: takosan/sim2022
    strategy:
      matrix:
        compiler: [g++-10, clang++-12]
        generator: [Unix Makefiles, Ninja]

    steps:
    - name: Checkout repo and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
        cmake -B ./build \
          -G="${{matrix.generator}}" \
          -DCMAKE_CXX_COMPILER=${{matrix.compiler}} \
          -DENABLE_WERROR=${{matrix.enable_werror}} \
          -DCMAKE_BUILD_TYPE=Release \
          -DSKIP_CLANG_FORMAT=ON \
          -DENABLE_LOG=OFF

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ./build --config Release -j

    - name: Perf
      working-directory: ./build/bin
      run: |
        riscv32-unknown-elf-gcc -O0 -e main -nostdlib -march=rv32g ../../test/e2e/simulator/8-queens.c -o 8q && \
        ./simulator 8q --print-perf
